### ISSUE TITLE
Distinct requirements for PR, branch, and cron builds

### ISSUE THREAD

**Issue by marcospereira** [playframework/play-meta#103]
## Distinct requirements for PR, branch, and cron builds

Let's define requirements that are more appropriate for each one of the types of builds.

### Versions

Primary and secondary versions are:

#### `master` branch

| What  | Primary  | Secondary |
|:------|:---------|:----------|
| Scala | `2.13.0` | `2.12.8`  |
| Java  | `8`      | `11`      |
| sbt   | `1`      | `0.13`    |

#### stable supported branches

| What  | Primary  | Secondary                               |
|:------|:---------|:----------------------------------------|
| Scala | `2.12.8` | `2.11.12` and `2.13.0` where applicable |
| Java  | `8`      | `11` where applicable                   |
| sbt   | `1`      | `0.13`                                  |

#### pull requests

1. docs: check format and headers
1. docs: run tests
1. framework: check format, headers and binary compatibility*
1. framework: run tests using main Scala version and Java version
1. framework: run scripted tests using main sbt version and Java version

<sub>
\* These are lightweight enough to run cross scala versions
</sub>

#### branches

All pull requests jobs plus:

1. framework: run tests using secondary Scala version and main Java version
1. framework: run scripted tests using secondary sbt version and main Java version

#### crons

All branches jobs plus:

1. framework: run tests using the main Scala version and secondary Java version
1. framework: run scripted tests using main sbt version and secondary Java version

_Originally posted by @marcospereira in https://github.com/playframework/play-meta/issues/98#issuecomment-511415403_

**Comment by mkurz** [comment]
I don't  think this matters anymore... It's from old ancient times we used Travis, we figures out our system with GitHub actions now.
