### ISSUE TITLE
Reconcile DevMode-SSL support between play and lagom

### ISSUE THREAD

**Issue by ignasi35** [playframework/play-meta#12]
Current approach to enable and setup SSL for Dev Mode in Play and Lagom is differs. The main cause is Lagom's multi-project nature. Other differences are the use of a self-signed cert or a self-signed CA with custom certs, the existence of a service gateway, ...

For example: Currently Play uses  `-Dhttps.port=<valid number>` to enable SSL in dev mode. That doesn't work on Lagom. A valid approach to Play later (and that can then be inherited by Lagom) is to have something like `-Dhttps.enabled=true`.

Credit: @marcospereira  :-)

**Comment by mkurz** [comment]
I don't think this will happen anymore.
