### ISSUE TITLE
Preparations for Lagom 1.6.0 GA

### ISSUE THREAD

**Issue by marcospereira** [playframework/play-meta#135]
- [x] Update Play 2.8.0 GA
  - [x] Update a few other upstream deps [lagom#2479](https://github.com/lagom/lagom/pull/2479)
- [x] Check whitesource report
- [x] Review migration guides
- [x] Review issues triaging and [milestones](https://github.com/lagom/lagom/milestone/33)

**Comment by ignasi35** [comment]
> Check whitesource report

If I'm reading correctly, the only violation in Lagom's whitesource report for the `1.6.x` branch is `"jakarta.transaction" % "jakarta.transaction-api" % "1.3.3"`. That is a [transitive dependency from Play](https://github.com/playframework/playframework/blob/2.8.x/project/Dependencies.scala#L153) so we should get it fixed there before releasing `2.8.0-GA`. If we add this violation to the exceptions list for Play, then the same can be done for Lagom.

cc @marcospereira

**Comment by ignasi35** [comment]
> If I'm reading correctly, the only violation in Lagom's whitesource report for the `1.6.x` branch is `"jakarta.transaction" % "jakarta.transaction-api" % "1.3.3"`. That is a [transitive dependency from Play](https://github.com/playframework/playframework/blob/2.8.x/project/Dependencies.scala#L153) [](/playframework/playframework/blob/HEAD@{2019-11-21T12:43:17Z}/project/Dependencies.scala#L153) so we should get it fixed there before releasing `2.8.0-GA`. If we add this violation to the exceptions list for Play, then the same can be done for Lagom.

So, I have done completely crazy:

 - I've checked out the `2.8.x` branch of Play. Then I removed the dependency `"jakarta.transaction" % "jakarta.transaction-api" % "1.3.3"` and everything still compiles. 🙃

**Comment by dwijnand** [comment]
jakarta.transaction-api shouldn't be a violation, because it's dual-licensed.  You just need to override it every time...

**Comment by ignasi35** [comment]
> jakarta.transaction-api shouldn't be a violation, because it's dual-licensed. You just need to override it every time...

Done! Thanks @dwijnand
