### ISSUE TITLE
Be JDK11 first

### ISSUE THREAD

**Issue by ignasi35** [playframework/play-meta#146]
Play, Lagom and all the related libraries and satellite projects should be 100% compilable, runnable and releasable using JDK11.

The output bytecode must target "1.8".

The javadocs must be produced by JDK11's `javadoc`.

Here's a list of tasks:

 - [ ] use a JDK11-ready release environment (currently `vegemite` is JDK8 only)
 - [ ] fix javadocs generation in [omnidoc](https://github.com/playframework/omnidoc/issues/106)

Runs all CI jobs in JDK11 (and some in JDK8 for regression tests)

 - [ ] play itself 
 - [ ] lagom itself 
 - [ ] ...

**Comment by ihostage** [comment]
Superseded by #244
