### ISSUE TITLE
Use TravisCI snippet import to reuse code

### ISSUE THREAD

**Issue by ignasi35** [playframework/play-meta#150]
See https://docs.travis-ci.com/user/build-config-imports/

The https://github.com/playframework/play-ws/pull/460 reminded me of the feature in TravisCI that allows importing snippets. I haven't tested it but I think the playframework and lagom ecosystems have a lot (and I mean A LOT) of duplicate snippets in the `.travis.yml` over all the repos.

**Comment by mkurz** [comment]
Travis is a thing from the past.
