### ISSUE TITLE
Setup Mergify for all Play's repos

### ISSUE THREAD

**Issue by renatocaval** [playframework/play-meta#16]
This is a list of Play repos that still need to be Mergified:

- [x] https://github.com/playframework/play-scala-grpc-example
- [ ] https://github.com/playframework/omnidoc
- [ ] https://github.com/playframework/play-ebean
- [x] https://github.com/playframework/play-grpc
- [ ] https://github.com/playframework/play-json
- [ ] https://github.com/playframework/play-mailer/
- [ ] https://github.com/playframework/play-ws
- [ ] https://github.com/playframework/playframework.com
- [ ] https://github.com/playframework/scalatestplus-play
- [ ] https://github.com/playframework/twirl

## Requires Mergify installed in Lightbend organisation

- [x] https://github.com/lightbend/play-team
- [x] https://github.com/lightbend/example-code-service/
- [x] https://github.com/lightbend/templatecontrol - this is done, but not working because mergify is no enable on the org.

**Comment by dwijnand** [comment]
Duplicate by https://github.com/playframework/play-meta/issues/24

All non-community-driven repos have been done.
