### ISSUE TITLE
Form a steering committee

### ISSUE THREAD

**Issue by ennru** [playframework/play-meta#189]
The Play community should identify community members/contributors that are appointed to make decisions on the community's behalf.

It might be a good idea to appoint individuals responsible for the different repos within the Play GitHub organisation as some sub-project have a life of their own.

**Comment by ennru** [comment]
This interview describes how JHipsters elect a core team within active contributors.
https://blog.opencollective.com/jhipsters-bounty-system-and-how-it-saved-the-project/

It even describes how JHipster uses bug bounties to give money to contributors.

**Comment by ennru** [comment]
Currently suggested people as founding members:
- @gmethvin
- @octonato 
- @mkurz

**Comment by BillyAutrey** [comment]
I'm happy to participate here as well, if there's room.

**Comment by mkurz** [comment]
@BillyAutrey added

**Comment by mkurz** [comment]
Let's close this. People had their chance to join and still can request to join later.
I already set up the "Steering Committee" GitHub team, were we can discuss further (just waiting for Bill to accept the invitation)
