### ISSUE TITLE
Define different levels of contribution

### ISSUE THREAD

**Issue by mkurz** [playframework/play-meta#192]
Open for discussion.

Should we define different levels of contribution?
We probably don't have to, look at https://socket.io/ or https://svelte.dev/ - they just list all their sponsors, without making a distinction between them.
However, it probably makes sense that sponsors that give a monthly recurring (more than the average) amount, should be listed as "special" sponsor.
Looking at JHipster, they have 4 levels (besides the default "backer" level): bronze, silver, gold, platinum (see https://www.jhipster.tech/sponsors/)
The question is, should (and can?) we offer certain benefits based on the level a sponsor has (besides listing the different levels with company logos on the website and the GitHub repo).

Summarizing the benefits we could offer, dependent on the level:
- [x] Mention on https://www.playframework.com/
 - Examples without levels: https://socket.io/, https://svelte.dev/
 - Example with levels: https://www.jhipster.tech/ (scroll down to "Sponsors & Backers")
- [x] Mention in the README in the Play GitHub repo
- [x] Mention in the release notes
- [ ] Company logos on all https://www.playframework.com/ page footers (including docs)
- [x] We could even add a default welcome message to the core `PlayService` plugin, so I think basically everyone that uses Play should see a message like (as long as they don't override the welcome message):
```
$ sbt
[info] welcome to sbt 1.5.5 (Eclipse Foundation Java 11.0.12)
[info] loading global plugins from /home/mkurz/.sbt/1.0/plugins
...
[info] loading settings for project foo from build.sbt,version.sbt ...
[info] ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[info] 
[info] ** Have a great day using Play! **
[info] 
[info] The Play Framework is sponsored by Informaticon AG (https://informaticon.com) and many more!
[info] If you like Play, please support it as well on https://opencollective.com/playframework
[info] 
[info] ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[info] sbt server started at local:///home/mkurz/.sbt/1.0/server/5d609ed20d17a85f78c0/sock
[info] started sbt server
[Foo] $ 
```
We could rotate the platinum/gold/whatever-we-decide sponsors in this message.

If we decide to use a bug bounty system like described in #190, we could also offer benefits based on that bounties, like JHipster has:
- [ ] "The ability to create x “bug bounties” every month, non transferable. If all bug bounties are not created by the end of the month, the remaining ones are lost."

**Comment by gmethvin** [comment]
I think if someone wants to be a _sponsor_—meaning we advertise for them—there should be some minimum donation amount. I think maybe $1000/month is a good level. We can always adjust as we get more companies.

It might be simplest to start with one sponsorship level. That would get your logo on the website and a mention in the release notes. I like the idea of including sponsors in the welcome message, but maybe we can reserve that for a higher sponsorship level.

I'm not sure how exactly to handle one-time donations. A simple approach would be to treat a one time donation of `$X` as equivalent to 12 monthly donations of `$X/12` per month. Open Collective has an API, so technically we could write something that determines the "current" sponsors using an arbitrarily complex set of rules, but I'd like to keep it simple enough that people can easily understand.

**Comment by mkurz** [comment]
OK, let's start with $1000/month. We can adjust that later anyway. I will have a look into the OpenCollective API so we are able to include a list all backers and premium sponsors on the play website before finally announce the Open Collective.

**Comment by mkurz** [comment]
So everyone is OK that donations with an amount of $1000+/month are called "premium sponsors"? (We can adjust that later anyway).
I am in the process of updating the website and adding a "sponsors" page to communicate why Play needs sponsoring and what the benefits of a premium sponsorship are.

**Comment by mkurz** [comment]
OK, what do you think about: Let's make $1200, because OpenCollective takes a 10%, so that makes $1080, minus payment provider fees (depending on what a sponsors uses) this will be at least $1000 or maybe up to $1070? Is that fair for you?
I will communicate that on the sponsors page I am adding to the website soon as well.

**Comment by mkurz** [comment]
So we have the USD 1200,- premium tier for now and to be honest that probably will not change soon, because we first have to even get more sponsors to think about other tiers. Closing for now.
