### ISSUE TITLE
Choose a chat platform

### ISSUE THREAD

**Issue by ennru** [playframework/play-meta#193]
Lightbend has a Slack channel with external Play contributors `#ext-play-maintainers`.
We are OK to keep that around but to make the synchronous chat more open, I suggest the steering committee may choose a different solution.

**Comment by ihostage** [comment]
@ennru How about [Play Discuss Forum](https://discuss.lightbend.com/c/play/8) hosted on Lightbend?
Should we choose a different place for the forum? I think it can be matters for the chat platform choice.

**Comment by mkurz** [comment]
@ihostage We could either host our own Discuss and migrate the data over to our instance. Or we just switch to GitHub Discussions, which might make sense because I guess it will have a good integration with issues and pull requests (also people don't have to sign up to an extra plattform, they can just use their GitHub account).
Examples:
* https://github.com/nodejs/node/discussions
* https://github.com/laravel/framework/discussions

Docs: https://docs.github.com/en/discussions

**Comment by ennru** [comment]
Right, I assume we can keep that forum. Let me check internally.
Or are there any objections about the independence/openness?

**Comment by mkurz** [comment]
> Or are there any objections about the independence/openness?

No, from my side not really. I was just thinking maybe it Play is it's own project and we are moving stuff anyway, maybe it makes sense to also move away from the Discuss Forum to GitHub discussions.

**Comment by mkurz** [comment]
Also about a chat platform: We are using slack right now, however do we need such a chat plattform? (Maybe yes, just thinking out loud) Maybe we (the "steering committee") can just use GitHub team discussions: https://docs.github.com/en/organizations/collaborating-with-your-team/about-team-discussions (which is a way to have private conversations between team members as far as I understand)
I did not really look into that yet however.

**Comment by ihostage** [comment]
> Or are there any objections about the independence/openness?

Nop 😄 But I agree with Matthias, that if many member activities will be done in one platform (GitHub in our case) it can be easy and very useful for team.

**Comment by ennru** [comment]
We at Lightbend are happy to continue hosting it, but we can only offer very few seats for moderation.

**Comment by SethTisue** [comment]
note that the Scala Discord has a #playframework channel these days

**Comment by octonato** [comment]
I think the original discussion was about the chat channel we have in Slack, but I agree about the forum. It would be better to move out of [discuss.lightbend.com](http://discuss.lightbend.com). GitHub discussion sounds good to me and I think that strategically we should avoid yet another thing to manage. So, less friction the better. 

About chat, we have Gitter, but it really sucks and seems to be left behind. I'm happy that we now have a #playframework channel in the Scala Discord. Seems that the Scala community is getting much more active in Discord then in Gitter. 

We don't need to start a Play Discord channel, IMO. Moving our chat to the Scala Discord seems to be a good thing for Play. 

Btw, here is a link for the Discord channel in case you are not there yet: https://discord.gg/aUnCN3Km

**Comment by mkurz** [comment]
> GitHub discussion sounds good to me and I think that strategically we should avoid yet another thing to manage. So, less friction the better.

Agree.

> I'm happy that we now have a #playframework channel in the Scala Discord.

Didn't know that :wink: I just joined, thanks.

**Comment by mkurz** [comment]
I created the "Steering Committee" GitHub team, I will invite all the members.

**Comment by mkurz** [comment]
Closing, since we came up with a decision yesterday.
We will discuss about moving to GitHub discussions next steering comittee meeting.
