### ISSUE TITLE
Decide how we handle EOL of "old" Play versions

### ISSUE THREAD

**Issue by mkurz** [playframework/play-meta#197]
Should we keep the strategy Lightbend had? Which means after exactly one year after a major release the previous major release is becoming EOL?
AFAIK some people wish that we support older Play versions longer, however that is a matter of who can invest time to maintain this old versions (also bascially a matter of funding).

Anyway, I think we should also publish the EOL strategy somewhere in the documentation, because I think it never was and people were asking about it every now and then.

**Comment by mkurz** [comment]
We didn't completely nail that one down, however:
* We definitely need to make clear that users do have to migrate to a next major version asap. Specially important to communicate that to sponsors.
* Probably we will do 6 month of bug fix backports and additional 6 months of security fixes. That gives users 1 year to upgrade.
* IMHO if someone wants to have something backported after 1 year they should pay for it (via Opencollective or directly to the maintainer that does that)

**Comment by ihostage** [comment]
I agree with 6+6 EOL strategy 👌 It's honestly.

**Comment by octonato** [comment]
I agree with the  6+6 EOL strategy. 

I'm reticent about backporting all bugs. If it's a serious bug (or regression) in the 6 months following a release, I think it's ok. But maybe not all bugs. 

Very often there is a workaround for a bug or the bug touches a corner case. In such cases, we should be able to say that the bug won't be backported, IMO.

Of course, that all depends on how easily we can cut a new release. If the backport is an easy one (done by mergify) and releasing is just about adding a tag, then I don't mind. 

But if we need to backport manually and then release manually for a bug that has a workaround or touches a corner case, then I think we should be able to just skip it.

The hard part is how and where to draw a line.

**Comment by ihostage** [comment]
@mkurz Is it still actual? Looks like we can close it because EOL strategy is described in https://www.playframework.com/documentation/2.9.x/General#End-of-life-(EOL)-dates

**Comment by mkurz** [comment]
Yes, done
