### ISSUE TITLE
Associate users to community sonatype profile

### ISSUE THREAD

**Issue by mkurz** [playframework/play-meta#199]
There is a new sonatype profile, `com.typesafe.play`. We will need to associate our sonatype users to this new profile (My sonatype username is `mkurz`)

**Comment by ihostage** [comment]
My username: `hostage`.
Maybe we should create a new account (`play_contributors` as variant) and use it for CI tasks?

**Comment by octonato** [comment]
Also, Sonatype offers this services for free for public repos in GitHub. We can integrate with it.

**Comment by mkurz** [comment]
We have an organization-wide sonatype user (`playframework`) now, credentials are set up and publishing already works :rocket: (e.g. https://github.com/playframework/play-json/runs/4901779699)
