### ISSUE TITLE
Define roadmap for Play 2.9 / clean up milestones

### ISSUE THREAD

**Issue by mkurz** [playframework/play-meta#202]
We do have a 2.9 milestone, and most of the assigned issues do make sense, but in general I want to clean up other milestones and define in more detail what we want to see in Play 2.9.

**Comment by ihostage** [comment]
Roadmap is pubic now 🎉 
https://github.com/orgs/playframework/projects/3/views/2

**Comment by mkurz** [comment]
Let's call this done.
