### ISSUE TITLE
Migrate to GitHub Actions

### ISSUE THREAD

**Issue by ihostage** [playframework/play-meta#204]
- [x] interplay
https://github.com/playframework/interplay/pull/203
- [x] anorm
https://github.com/playframework/anorm/pull/455
- [x] play-slick
https://github.com/playframework/play-slick/pull/672
https://github.com/playframework/play-slick/pull/673
https://github.com/playframework/play-slick/pull/674
https://github.com/playframework/play-slick/pull/676
https://github.com/playframework/play-slick/pull/677
https://github.com/playframework/play-slick/pull/678
- [x] omnidoc
https://github.com/playframework/omnidoc/pull/197
https://github.com/playframework/omnidoc/pull/199
- [ ] playframework
https://github.com/playframework/playframework/pull/11115
https://github.com/playframework/playframework/pull/11116
https://github.com/playframework/playframework/pull/11142
https://github.com/playframework/playframework/pull/11247
https://github.com/playframework/playframework/pull/11249
https://github.com/playframework/playframework/pull/11259
https://github.com/playframework/playframework/pull/11262
https://github.com/playframework/playframework/pull/11269
https://github.com/playframework/playframework/pull/11270
https://github.com/playframework/playframework/pull/11271
https://github.com/playframework/playframework/pull/11285
- [x] play-json
https://github.com/playframework/play-json/pull/682
https://github.com/playframework/play-json/pull/693
https://github.com/playframework/play-json/pull/703
https://github.com/playframework/play-json/pull/746
https://github.com/playframework/play-json/pull/749
https://github.com/playframework/play-json/pull/757
https://github.com/playframework/play-json/pull/758
- [x] play-samples
https://github.com/playframework/play-samples/pull/165
https://github.com/playframework/play-samples/pull/166
https://github.com/playframework/play-samples/pull/167
- [x] cachecontrol
https://github.com/playframework/cachecontrol/pull/221
- [x] twirl
https://github.com/playframework/twirl/pull/483
https://github.com/playframework/twirl/pull/507
https://github.com/playframework/twirl/pull/517
https://github.com/playframework/twirl/pull/519
https://github.com/playframework/twirl/pull/520
https://github.com/playframework/twirl/pull/521
- [x] play-doc
https://github.com/playframework/play-doc/pull/145
- [x] play-java-seed.g8
https://github.com/playframework/play-java-seed.g8/pull/105
https://github.com/playframework/play-java-seed.g8/pull/106
- [x] play-scala-seed.g8
https://github.com/playframework/play-scala-seed.g8/pull/162
- [x] playframework.com
https://github.com/playframework/playframework.com/pull/490
https://github.com/playframework/playframework.com/pull/491
- [x] play-ws
https://github.com/playframework/play-ws/pull/637
https://github.com/playframework/play-ws/pull/639
https://github.com/playframework/play-ws/pull/642
https://github.com/playframework/play-ws/pull/644
https://github.com/playframework/play-ws/pull/645
https://github.com/playframework/play-ws/pull/670
https://github.com/playframework/play-ws/pull/672
https://github.com/playframework/play-ws/pull/673
https://github.com/playframework/play-ws/pull/676
https://github.com/playframework/play-ws/pull/677
https://github.com/playframework/play-ws/pull/680
- [x] play-webgoat
https://github.com/playframework/play-webgoat/pull/55
https://github.com/playframework/play-webgoat/pull/58
https://github.com/playframework/play-webgoat/pull/59
https://github.com/playframework/play-webgoat/pull/62
- [x] play-grpc
https://github.com/playframework/play-grpc/pull/415
https://github.com/playframework/play-grpc/pull/417
https://github.com/playframework/play-grpc/pull/418
https://github.com/playframework/play-grpc/pull/419
- [x] play-soap
https://github.com/playframework/play-soap/pull/276
https://github.com/playframework/play-soap/pull/278
https://github.com/playframework/play-soap/pull/279
https://github.com/playframework/play-soap/pull/280
https://github.com/playframework/play-soap/pull/309
https://github.com/playframework/play-soap/pull/314
https://github.com/playframework/play-soap/pull/315
- [x] play-file-watch
https://github.com/playframework/play-file-watch/pull/168
- [x] play-ebean
https://github.com/playframework/play-ebean/pull/283
- [x] play-socket.io
https://github.com/playframework/play-socket.io/pull/215
- [x] play-mailer
https://github.com/playframework/play-mailer/pull/215
- [x] scalatestplus-play
https://github.com/playframework/scalatestplus-play/pull/373
- [x] netty-reactive-streams
https://github.com/playframework/netty-reactive-streams/pull/89

**Comment by ihostage** [comment]
A few links for work on reusing and starter workflows:
* [Using release management for actions](https://docs.github.com/en/actions/creating-actions/about-custom-actions#using-release-management-for-actions)
* [Reusing workflows](https://docs.github.com/en/actions/using-workflows/reusing-workflows)
* [Starter workflows](https://docs.github.com/en/actions/using-workflows/creating-starter-workflows-for-your-organization)

**Comment by ihostage** [comment]
Cross-link to https://github.com/actions/runner/issues/1182
YAML anchors can help us in some cases.

**Comment by ihostage** [comment]
@mkurz Matthias, for [playframework.com](https://github.com/playframework/playframework.com) repo a [few tasks commented](https://github.com/playframework/playframework.com/blob/201c0188ea16227206d5489800285198154ad875/.github/workflows/build-test.yml#L16-L24) that why I don't toggled this repo 🤷‍♂️ Are you think we are done for him? 😄

**Comment by mkurz** [comment]
Yes, it's done. Not 100% sure why I didn't remove the comments anymore, probably because I wanted to add code validations...

**Comment by ihostage** [comment]
I think we are ready to close this 🥳 It was a good hunt 😄
