### ISSUE TITLE
Set up (at least) email inboxes for playframework.com

### ISSUE THREAD

**Issue by mkurz** [playframework/play-meta#205]
We probably want a couple of @playframework.com email adresses. E.g. I had to enter an email address in Travis for billing purposes.
Also @ihostage suggested to set up an email address which we can use to sign up for Sonatype.

What can we do right now and which choice do we have?

**Solution 1**: Use a business mail hosting solution:
* Set up a Google Workspace account, USD 6/user/month: https://workspace.google.com/intl/en/pricing.html
* Set up a Zoho account, e.g. MAIL LITE for EUR 0,90/user/month: https://www.zoho.com/mail/zohomail-pricing.html
* Set up a ProtonMail account, EUR 8/user/month (or EUR 6.25/user/month annually): https://protonmail.com/business/pricing
* any others (amazon, etc.)?

I would prefer Google, however I will just go ahead and reach out all of the listed services support and ask them if they could provide us the service for free, because we are a OSS project. I might offer them that we mention them in a "thank you section" on the website and github readme, just like JHipster does (besides the premium sponsors): https://www.jhipster.tech/contributing-companies/

**Solution 2**: Somehow forward emails via another service to our private mail addresses:
* See [this discussion](https://stackoverflow.com/questions/17382003/using-mx-records-to-forward-email-to-another-domain)
  * https://improvmx.com/ (they have a free plan that should work for us)
  * Use a service like https://www.mailgun.com/ and use its "routing" feature to forward the incoming mails, however it looks that is a paid service now as well (according to the stackoverflow discussion USD 35,- per year). Not sure yet if other service like https://sendgrid.com/ or https://www.mailjet.com/ offer something similar and how much it is.
  *  Adding to the last point, now that I know that the Play website is hosted on an AWS EC2 instance, I think it would make sense to also set up an AWS account for Play and just migrate the current VM over the official Play account (we can discuss that in [#451](https://github.com/playframework/playframework.com/issues/451)). As part of that we could also use a AWS service (SES?) to forward incoming emails to our private addresses.
 * Of course we could setup exim/sendmail/postfix on a vm ourselves (like on the vm we will host the play website on), point the mx record to it and configure mail forwarding. It's a one time setup. Not sure however we want to this is ourselves, because if it makes troubles someone has to fix it and we may loose emails in between...

Disadvantage of solution 2: We can not really setup up shared inboxes/mailing lists, however could still cc each other. Also email send would be from our private mail addresses and not @playframework.com, however that should not much of a problem, because I think, except for sponsors, we would not really send out lots of mails.

My opinion: I would prefer not to use our private email address, because if someone leaves the steering committee and new members join, they would not have access to all the old emails to catch up. Also I think to make things transparent for other sc members it would be good if we have an official mail address with shared inbox/mailing list which we use to communicate sponsors, so that everyone is aware of the current state.

If we come to a decision, what needs to be done:
* I guess someone from Lightbend has to update the MX record to point to the service we use.
* Or as part of [#452](https://github.com/playframework/playframework.com/issues/452), where we move playframework.com domain to OpenCollective and I am just waiting for them now to get the process started: https://github.com/opencollective/opencollective/issues/4880#issuecomment-980011604 Actually its not complicated and shouldn't take long, OpenCollective just needs to set the same nameserver which are used right now, and everything should continue to work. Then we could set DNS entries ourselves.

**Comment by ihostage** [comment]
**Solution 1(additional):**
* Set up a Yandex 360. For our case is free. https://yandex.com/support/business/payment.html#payment__free_plan

**Comment by ihostage** [comment]
**Solution 3:** Use a public mail service (Gmail for example)
 
We create a few e-mail addresses (`play_steering_committee@gmail.com`, `play_mainteiners@gmail.com`, etc) and we share their credentials with steering committee members. Also, we can configure forwarding messages from these addresses to our personal addresses but we need to be careful with replies to these messages from personal accounts.

**Comment by ihostage** [comment]
My opinion is that we should find a free variant for solution 1 and have a few e-mail addresses in the `playframework.com` domain.

Example addresses: 
* for payment activities - `billing|payment@playframework.com`
* for  activities of maintaining (CI notifications, Sonatype notifications, e-mail in PGP, developers e-mail in POM, etc) -`maintainers|contributors|developers@playframework.com`
* for sponsors - `sponsors|donate@playframework.com`
* for some notifications - `noreply@playframework.com`

**Comment by AlexITC** [comment]
A similar idea to @ihostage would be to create a single mailbox with a cheap provider (like zoho) and define a `catch-all` or many aliases, this way, you pay for 1 account but you can send emails from any account when needed.

**Comment by ennru** [comment]
Lightbend is happy to continue sponsorship of Play by managing the playframework.com domain and setting up email forwards if that's desired.

**Comment by mkurz** [comment]
So let's keep things simple: We do have the Gmail address now, we will just forward contact@playframework.com to it (and maybe others).

**Comment by mkurz** [comment]
So we decided that Lightbend keeps the domain for now. We have a free GMail address which gets email forwarded from contact@playframework.com and security@playframework.com.

BTW: Google will drop their legacy free edition of GSuite later this year. That doesn't affect us of course, however there is a nice discussion on hacker news about alternatives: https://news.ycombinator.com/item?id=29996432 In case we migrate away maybe there are helpful hints (like Cloudflare Email Routing, etc.) we haven't considered yet.
