### ISSUE TITLE
Review the tutorials listing in the docs

### ISSUE THREAD

**Issue by ennru** [playframework/play-meta#206]
The [Tutorials page](https://www.playframework.com/documentation/2.8.x/Tutorials) lists a number of both Java and Scala example projects with their GitHub repos.

Lightbend's [developer.lightbend.com](https://developer.lightbend.com/start/?group=play) contains a few more examples.

Review if anything more from the Lightbend listing should be referenced in the docs directly and remove the reference to the "Lightbend Tech Hub".

**Comment by mkurz** [comment]
Following projects are listed on the Lightbend page but not in the Play docs:
* https://developer.lightbend.com/start/?group=play&project=play-samples-play-scala-hello-world-tutorial (https://github.com/playframework/play-samples/tree/2.8.x/play-scala-hello-world-tutorial)
* https://developer.lightbend.com/start/?group=play&project=play-samples-play-java-hello-world-tutorial (https://github.com/playframework/play-samples/tree/2.8.x/play-java-hello-world-tutorial)
* https://developer.lightbend.com/start/?group=play&project=play-samples-play-scala-starter-example (https://github.com/playframework/play-samples/tree/2.8.x/play-scala-starter-example)
* https://developer.lightbend.com/start/?group=play&project=play-samples-play-java-starter-example (https://github.com/playframework/play-samples/tree/2.8.x/play-java-starter-example)
* https://developer.lightbend.com/start/?group=play&project=play-samples-play-scala-tls-example (https://github.com/playframework/play-samples/tree/2.8.x/play-scala-tls-example)
* https://developer.lightbend.com/start/?group=play&project=play-scala-seed (https://github.com/playframework/play-scala-seed.g8/tree/2.8.x)
* https://developer.lightbend.com/start/?group=play&project=play-java-seed (https://github.com/playframework/play-java-seed.g8/tree/2.8.x)

**Comment by mkurz** [comment]
Fixed by https://github.com/playframework/playframework/pull/11988
