### ISSUE TITLE
Make use of sbt-github-actions plugin?

### ISSUE THREAD

**Issue by mkurz** [playframework/play-meta#219]
I didn't look close, so not sure if that makes sense for us, but we may can generate the .yml files automatically with https://github.com/djspiewak/sbt-github-actions
Just a reminder to look at that later...

**Comment by ihostage** [comment]
It make sense. But I'll leave here some my thoughts by hot pursuits:
1. Generator generate yml per repo and if you need change something (version of one action for example), you should regenerate yaml for every repo that very expensive. 😞 
2. Generator can't generate universal yml by many different sbt files like in our case.
3. I like a full control of CI scripts for decrease a risks 😊

**Comment by mkurz** [comment]
I think we will not switch to sbt-github-actions anymore :wink:
