### ISSUE TITLE
Actualize `repos.md`

### ISSUE THREAD

**Issue by ihostage** [playframework/play-meta#221]
I think needs to actualize [repos.md](https://github.com/playframework/play-meta/blob/main/repos.md) for us itself and for community.

**Comment by mkurz** [comment]
I don't think this is necessary anymore, we have https://github.com/playframework/play-meta/blob/main/.github/ISSUE_TEMPLATE/all-repos-issue.md now. I mean who is this information for? We know which repos we have, also I don't care so much abou the Lagom ones.
I hope you are ok with closing this, if not let me know.

**Comment by ihostage** [comment]
Yep, it's ok 👌 
I created this issue before we created template for all repos 😄
