### ISSUE TITLE
Drop unused webhooks

### ISSUE THREAD

**Issue by ihostage** [playframework/play-meta#226]
Some repositories has unused webhooks. I think we should keep only two: **Discord** and **Lightbend CLA**. WDYT?

Fox example
![2022-05-18_16-36-35](https://user-images.githubusercontent.com/817328/169052161-d1d6d569-466e-457e-acfc-bba0830794b3.png)

- [x] [playframework](https://github.com/playframework/playframework/settings/hooks)
- [x] [playframework.com](https://github.com/playframework/playframework.com/settings/hooks)
- [x] [interplay](https://github.com/playframework/interplay/settings/hooks)

- [x] [play-doc](https://github.com/playframework/play-doc/settings/hooks)
- [x] [play-ebean](https://github.com/playframework/play-ebean/settings/hooks)
- [x] [play-file-watch](https://github.com/playframework/play-file-watch/settings/hooks)
- [x] [play-grpc](https://github.com/playframework/play-grpc/settings/hooks)
- [x] [play-json](https://github.com/playframework/play-json/settings/hooks)
- [x] [play-mailer](https://github.com/playframework/play-mailer/settings/hooks)
- [x] [play-samples](https://github.com/playframework/play-samples/settings/hooks)
- [x] [play-slick](https://github.com/playframework/play-slick/settings/hooks)
- [x] [play-soap](https://github.com/playframework/play-soap/settings/hooks)
- [x] [play-socket.io](https://github.com/playframework/play-socket.io/settings/hooks)
- [x] [play-webgoat](https://github.com/playframework/play-webgoat/settings/hooks)
- [x] [play-ws](https://github.com/playframework/play-ws/settings/hooks)

- [x] [anorm](https://github.com/playframework/anorm/settings/hooks)
- [x] [cachecontrol](https://github.com/playframework/cachecontrol/settings/hooks)
- [x] [netty-reactive-streams](https://github.com/playframework/netty-reactive-streams/settings/hooks)
- [x] [omnidoc](https://github.com/playframework/omnidoc/settings/hooks)
- [x] [scalatestplus-play](https://github.com/playframework/scalatestplus-play/settings/hooks)
- [x] [twirl](https://github.com/playframework/twirl/settings/hooks)

- [x] [play-java-seed.g8](https://github.com/playframework/play-java-seed.g8/settings/hooks)
- [x] [play-scala-seed.g8](https://github.com/playframework/play-scala-seed.g8/settings/hooks)
- [x] [play-java-react-seed](https://github.com/playframework/play-java-react-seed/settings/hooks)
- [x] [play-scala-react-seed](https://github.com/playframework/play-scala-react-seed/settings/hooks)
- [x] [play-java-angular-seed](https://github.com/playframework/play-java-angular-seed/settings/hooks)
- [x] [play-scala-angular-seed](https://github.com/playframework/play-scala-angular-seed/settings/hooks)

- [x] [.github](https://github.com/playframework/.github/settings/hooks)
- [x] [play-meta](https://github.com/playframework/play-meta/settings/hooks)
- [x] [play-generated-docs](https://github.com/playframework/play-generated-docs/settings/hooks)

**Comment by mkurz** [comment]
Yes I know.  There are also other settings which need to by synchronised.

**Comment by mkurz** [comment]
Done 👍
