### ISSUE TITLE
Preserved PR title when merging/squashing

### ISSUE THREAD

**Issue by renatocaval** [playframework/play-meta#23]
Part of the discussion of Merge vs. Squash. 

One thing about merge is that GitHub automatically add a title similar to: 
"Merge pull request #pr-num from contributor/branch" 

When the history gets full of this it becomes hard to understand what was done on the project. You need to navigate to the PR to get the context. 

The idea is to change Mergify so it uses the PR title for both merge and squash. 

There are a few options here:

* use the same format as squash: "title (#pr-num)"
* put PR number in front, so it doesn't get cut-off for long titles: "#pr-num - title"
* tag the title with [merged] / [squashed] (optional)

**Comment by dwijnand** [comment]
Send a PR to Mergify. If accepted and once deployed we can start using Mergify for backports! <3

**Comment by dwijnand** [comment]
I think we've come to terms with how merged PRs look like.

Can revisit if we start to think differently.
