### ISSUE TITLE
Bump SBT to 1.7

### ISSUE THREAD

**Issue by ihostage** [playframework/play-meta#241]
- [x] [playframework](https://github.com/playframework/playframework)
https://github.com/playframework/playframework/pull/11349
- [x] [playframework.com](https://github.com/playframework/playframework.com)
https://github.com/playframework/playframework.com/pull/499
- [x] [interplay](https://github.com/playframework/interplay)
https://github.com/playframework/interplay/pull/207

- [x] [play-doc](https://github.com/playframework/play-doc)
https://github.com/playframework/play-doc/pull/150
- [x] [play-ebean](https://github.com/playframework/play-ebean)
https://github.com/playframework/play-ebean/pull/309
- [x] [play-file-watch](https://github.com/playframework/play-file-watch)
https://github.com/playframework/play-file-watch/pull/177
- [x] [play-grpc](https://github.com/playframework/play-grpc)
https://github.com/playframework/play-grpc/pull/426
- [x] [play-json](https://github.com/playframework/play-json)
https://github.com/playframework/play-json/pull/777
- [x] [play-mailer](https://github.com/playframework/play-mailer)
https://github.com/playframework/play-mailer/pull/220
- [x] [play-samples](https://github.com/playframework/play-samples)
https://github.com/playframework/play-samples/pull/171
- [x] [play-slick](https://github.com/playframework/play-slick)
https://github.com/playframework/play-slick/pull/688
- [x] [play-soap](https://github.com/playframework/play-soap)
https://github.com/playframework/play-soap/pull/326
- [x] [play-socket.io](https://github.com/playframework/play-socket.io)
https://github.com/playframework/play-socket.io/pull/227
- [x] [play-webgoat](https://github.com/playframework/play-webgoat)
https://github.com/playframework/play-webgoat/pull/67
- [x] [play-ws](https://github.com/playframework/play-ws)
https://github.com/playframework/play-ws/pull/696

- [x] [anorm](https://github.com/playframework/anorm)
https://github.com/playframework/anorm/pull/472
- [x] [cachecontrol](https://github.com/playframework/cachecontrol)
https://github.com/playframework/cachecontrol/pull/228
- [x] [~netty-reactive-streams~](https://github.com/playframework/netty-reactive-streams)

- [x] [omnidoc](https://github.com/playframework/omnidoc)
https://github.com/playframework/omnidoc/pull/203
- [x] [scalatestplus-play](https://github.com/playframework/scalatestplus-play)
https://github.com/playframework/scalatestplus-play/pull/365
- [x] [twirl](https://github.com/playframework/twirl)
https://github.com/playframework/twirl/pull/534

- [x] [play-java-seed.g8](https://github.com/playframework/play-java-seed.g8)
https://github.com/playframework/play-java-seed.g8/pull/109
- [x] [play-scala-seed.g8](https://github.com/playframework/play-scala-seed.g8)
https://github.com/playframework/play-scala-seed.g8/pull/166
- [x] [play-java-react-seed](https://github.com/playframework/play-java-react-seed)
https://github.com/playframework/play-java-react-seed/pull/53
- [x] [play-scala-react-seed](https://github.com/playframework/play-scala-react-seed)
https://github.com/playframework/play-scala-react-seed/pull/101
- [x] [play-java-angular-seed](https://github.com/playframework/play-java-angular-seed)
https://github.com/playframework/play-java-angular-seed/pull/47
- [x] [play-scala-angular-seed](https://github.com/playframework/play-scala-angular-seed)
https://github.com/playframework/play-scala-angular-seed/pull/55

- [x] [~.github~](https://github.com/playframework/.github)
- [x] [~play-meta~](https://github.com/playframework/play-meta)
- [x] [~play-generated-docs~](https://github.com/playframework/play-generated-docs)

**Comment by mkurz** [comment]
Everything done, omnidoc was the last one.
