### ISSUE TITLE
Remove Lightbend CLA from Mergify configuration

### ISSUE THREAD

**Issue by ihostage** [playframework/play-meta#243]
⚠️ **Also need remove CLA from webhook and branch protection rules in GH settings** ⚠️ 

- [x] [playframework](https://github.com/playframework/playframework)
https://github.com/playframework/playframework/pull/11424
- [x] [playframework.com](https://github.com/playframework/playframework.com)
https://github.com/playframework/playframework.com/pull/505
- [x] [interplay](https://github.com/playframework/interplay)
https://github.com/playframework/interplay/pull/209

- [x] [play-doc](https://github.com/playframework/play-doc)
https://github.com/playframework/play-doc/pull/152
- [x] [play-ebean](https://github.com/playframework/play-ebean)
https://github.com/playframework/play-ebean/pull/317
- [x] [play-file-watch](https://github.com/playframework/play-file-watch)
https://github.com/playframework/play-file-watch/pull/181
https://github.com/playframework/play-file-watch/pull/182
- [x] [play-grpc](https://github.com/playframework/play-grpc)
https://github.com/playframework/play-grpc/pull/433
- [x] [play-json](https://github.com/playframework/play-json)
https://github.com/playframework/play-json/pull/792
- [x] [play-mailer](https://github.com/playframework/play-mailer)
https://github.com/playframework/play-mailer/pull/222
- [x] [play-samples](https://github.com/playframework/play-samples)
https://github.com/playframework/play-samples/pull/175
- [x] [play-slick](https://github.com/playframework/play-slick)
https://github.com/playframework/play-slick/pull/692
- [x] [play-soap](https://github.com/playframework/play-soap)
https://github.com/playframework/play-soap/pull/318
- [x] [play-socket.io](https://github.com/playframework/play-socket.io)
https://github.com/playframework/play-socket.io/pull/235
- [x] [play-webgoat](https://github.com/playframework/play-webgoat)
https://github.com/playframework/play-webgoat/pull/68
- [x] [play-ws](https://github.com/playframework/play-ws)
https://github.com/playframework/play-ws/pull/699

- [x] [cachecontrol](https://github.com/playframework/cachecontrol)
https://github.com/playframework/cachecontrol/pull/234
- [x] [omnidoc](https://github.com/playframework/omnidoc)
https://github.com/playframework/omnidoc/pull/206
- [x] [scalatestplus-play](https://github.com/playframework/scalatestplus-play)
https://github.com/playframework/scalatestplus-play/pull/372
- [x] [twirl](https://github.com/playframework/twirl)
https://github.com/playframework/twirl/pull/543

- [x] [play-java-seed.g8](https://github.com/playframework/play-java-seed.g8)
https://github.com/playframework/play-java-seed.g8/pull/111
- [x] [play-scala-seed.g8](https://github.com/playframework/play-scala-seed.g8)
https://github.com/playframework/play-scala-seed.g8/pull/168

**Comment by mkurz** [comment]
Great Sergey! :partying_face: Thanks!
