### ISSUE TITLE
Release Play 2.9.0-RC1

### ISSUE THREAD

**Issue by mkurz** [playframework/play-meta#258]
## Preparing the release

Better to do this in advance:

* [x] [Triage issues][]

## Do the Release ([Full document](https://github.com/playframework/.github/blob/main/RELEASING.md))

* [x] [Release projects that Play depends on][]
  * [x] release [play-json][]
    * [x] Look for [PRs][play-json/prs] that should be merged.
    * [x] Look at [`status:needs-backport`][play-json/backport], [`status:needs-forwardport`][play-json/forwardport] issues/PRs (including closed ones).
    * [x] Look at issues/PRs tagged [milestone][play-json/milestones] version (including closed ones).
    * [x] Update any dependencies that are needed. (e.g JDK, Scala)
  * [x] release [play-ws][]
    * [x] Look for [PRs][play-ws/prs] that should be merged.
    * [x] Look at [`status:needs-backport`][play-ws/backport], [`status:needs-forwardport`][play-ws/forwardport] issues/PRs (including closed ones).
    * [x] Look at issues/PRs tagged [milestone][play-ws/milestones] version (including closed ones).
    * [x] Update any dependencies that are needed. (e.g JDK, Scala)
    * [x] Make sure play-ws uses new play-json
  * [x] release [twirl][]
    * [x] Look for [PRs][twirl/prs] that should be merged.
    * [x] Look at [`status:needs-backport`][twirl/backport], [`status:needs-forwardport`][twirl/forwardport], [`status:needs-backport-1.3`][twirl/backport-1.3] issues/PRs (including closed ones).
    * [x] Look at issues/PRs tagged [milestone][twirl/milestones] version (including closed ones).
    * [x] Update any dependencies that are needed. (e.g JDK, Scala)

* [ ] [Release Play itself][]
    * [x] Look for [PRs][play/prs] that should be merged.
    * [x] Look at [`status:needs-backport`][play/backport], [`status:needs-forwardport`][play/forwardport] issues/PRs (including closed ones).
    * [x] Look at issues/PRs tagged [milestone][play/milestones] version (including closed ones).
    * [x] Update any dependencies that are needed. (e.g JDK, Scala)
    * [x] Make sure play uses new play-json, play-ws, twirl

* [x] [Release external modules][]
  * [x] release [play-slick][]
  * [x] release [play-ebean][]
  * [x] release [scalatestplus-play][]
  * [ ] release [play-grpc][]

* [x] [Release omnidoc][]

* [x] [Update play-samples][]

* [x] [Update playframework.com][]
  * [x] [Update `.version` in `play-generated-docs`][]
  * [x] [Update `playReleases.json` and `changelog.md`][]
  * [x] [Deploy the website changes][]

* [x] [Announce][]
  * [x] Post on security mailing list if necessary
  * [x] Publish a release at <https://github.com/playframework/playframework/releases> with a corresponding discussion
  * [x] Tweet about the new release.
  * [x] Announce in the Play LinkedIn group: https://www.linkedin.com/groups/3818467/

* [ ] [Post release tasks][]

[Triage issues]: https://github.com/issues?utf8=%E2%9C%93&q=label%3Atriage+org%3Aplayframework+archived%3Afalse+
[Release projects that Play depends on]: https://github.com/playframework/.github/blob/main/RELEASING.md#step-0---release-projects-that-play-depends-on-play-json-play-ws-twirl
[Release Play itself]: https://github.com/playframework/.github/blob/main/RELEASING.md#step-1---release-play-itself
[Release external modules]: https://github.com/playframework/.github/blob/main/RELEASING.md#step-2---release-external-modules
[Release omnidoc]: https://github.com/playframework/.github/blob/main/RELEASING.md#step-3---release-omnidoc
[Update play-samples]: https://github.com/playframework/.github/blob/main/RELEASING.md#step-4---update-playframework-templates-and-seeds
[Update playframework.com]: https://github.com/playframework/.github/blob/main/RELEASING.md#step-6---update-playframeworkcom
[Update `.version` in `play-generated-docs`]: https://github.com/playframework/.github/blob/main/RELEASING.md#update-version-in-play-generated-docs
[Update `playReleases.json` and `changelog.md`]: https://github.com/playframework/.github/blob/main/RELEASING.md#update-playreleasesjson-and-changelogmd
[Update versions for Example Code Service]: https://github.com/playframework/.github/blob/main/RELEASING.md#update-versions-for-example-code-service
[Deploy the website changes]: https://github.com/playframework/.github/blob/main/RELEASING.md#deploy-the-website-changes
[Announce]: https://github.com/playframework/.github/blob/main/RELEASING.md#step-7---announce
[Post release tasks]: https://github.com/playframework/.github/blob/main/RELEASING.md#step-8---post-release-tasks

[play-grpc]: https://github.com/playframework/play-grpc
[play-json]: https://github.com/playframework/play-json
[play-slick]: https://github.com/playframework/play-slick
[play-ebean]: https://github.com/playframework/play-ebean
[play-ws]: https://github.com/playframework/play-ws
[scalatestplus-play]: https://github.com/playframework/scalatestplus-play
[twirl]: https://github.com/playframework/twirl

[play-json/prs]:         https://github.com/playframework/play-json/pulls
[play-json/backport]:    https://github.com/playframework/play-json/labels/status%3Aneeds-backport
[play-json/forwardport]: https://github.com/playframework/play-json/labels/status%3Aneeds-forwardport
[play-json/milestones]:  https://github.com/playframework/play-json/milestones?direction=asc&sort=due_date

[play-ws/prs]:         https://github.com/playframework/play-ws/pulls
[play-ws/backport]:    https://github.com/playframework/play-ws/labels/status%3Aneeds-backport
[play-ws/forwardport]: https://github.com/playframework/play-ws/labels/status%3Aneeds-forwardport
[play-ws/milestones]:  https://github.com/playframework/play-ws/milestones?direction=asc&sort=due_date

[twirl/prs]:          https://github.com/playframework/twirl/pulls
[twirl/backport]:     https://github.com/playframework/twirl/labels/status%3Aneeds-backport
[twirl/forwardport]:  https://github.com/playframework/twirl/labels/status%3Aneeds-forwardport
[twirl/backport-1.3]: https://github.com/playframework/twirl/labels/status%3Aneeds-backport-1.3
[twirl/milestones]:   https://github.com/playframework/twirl/milestones?direction=asc&sort=due_date

[play/prs]:          https://github.com/playframework/playframework/pulls
[play/backport]:     https://github.com/playframework/playframework/labels/status%3Aneeds-backport
[play/forwardport]:  https://github.com/playframework/playframework/labels/status%3Aneeds-forwardport
[play/backport-2.6]: https://github.com/playframework/playframework/labels/status%3Aneeds-backport-2.6
[play/milestones]:   https://github.com/playframework/playframework/milestones?direction=asc&sort=due_date

**Comment by mkurz** [comment]
https://github.com/playframework/play-file-watch/releases/tag/1.2.0

**Comment by mkurz** [comment]
https://github.com/sbt/sbt-web/releases/tag/1.5.0

**Comment by mkurz** [comment]
https://github.com/sbt/sbt-js-engine/releases/tag/1.3.0

**Comment by mkurz** [comment]
https://github.com/playframework/cachecontrol/releases/tag/2.3.0
https://repo1.maven.org/maven2/com/typesafe/play/cachecontrol_2.13/2.3.0/

**Comment by mkurz** [comment]
https://github.com/playframework/twirl/releases/tag/1.6.0
https://repo1.maven.org/maven2/com/typesafe/play/sbt-twirl_2.12_1.0/1.6.0/

**Comment by mkurz** [comment]
https://github.com/playframework/play-doc/releases/tag/2.2.0
https://repo1.maven.org/maven2/com/typesafe/play/play-doc_2.13/2.2.0/

**Comment by mkurz** [comment]
https://github.com/playframework/play-json/releases/tag/2.10.0
https://repo1.maven.org/maven2/com/typesafe/play/play-json_2.13/2.10.0/

**Comment by mkurz** [comment]
https://github.com/playframework/play-ws/releases/tag/2.2.0
https://repo1.maven.org/maven2/com/typesafe/play/play-ws-standalone_2.13/2.2.0/

**Comment by mkurz** [comment]
Bad news: sbt 1.9.5 introduced a compiler bug.

That means, I have to publish RC2 now, including all those libraries...
https://github.com/sbt/sbt/releases/tag/v1.9.5
> Update: ⚠️ sbt 1.9.5 is broken, because it causes Scala compiler to generate wrong class names for anonymous class on lambda. While we investigate please refrain from publishing libraries with it.
scala/bug#12868 (comment)

Eugene published 1.9.6 one hour ago with the fix: https://github.com/sbt/sbt/releases/tag/v1.9.6
He recommends re-publishing to stay safe: https://github.com/scala/bug/issues/12868#issuecomment-1721618123

So I was lucky to publish RC1 and all those other libraries within a 35 hours time window...

**Comment by ihostage** [comment]
😢😢😢

**Comment by mkurz** [comment]
https://github.com/playframework/playframework/releases/tag/2.9.0-RC2
https://twitter.com/playframework/status/1704255296762167406
https://www.linkedin.com/feed/update/urn:li:activity:7110025625863626754
https://www.reddit.com/r/scala/comments/16n4f89/play_290_release_candidate_available/
