### ISSUE TITLE
Publish snapshots for play-ws and play-json

### ISSUE THREAD

**Issue by marcospereira** [playframework/play-meta#29]
We already have snapshots for:

1. [Play](https://oss.sonatype.org/content/repositories/snapshots/com/typesafe/play/play_2.12/)
1. [Twirl](https://oss.sonatype.org/content/repositories/snapshots/com/typesafe/play/twirl-api_2.12/)

Besides play-ws and play-json, it could be good to also have snapshots for the downstream modules we maintain:

1. play-slick
1. scalatest+play

**Comment by mkurz** [comment]
We have snapshot again for play, play-ws, play-json, twirl,... and more to come.
