### ISSUE TITLE
lagom/shopping-cart-scala > hello world

### ISSUE THREAD

**Issue by dwijnand** [playframework/play-meta#33]
https://github.com/lagom/shopping-cart-scala now existing and as @jroper says:

> is no more complex than the hello world sample that we have, except it actually models a real-world domain problem, so it actually makes sense.

Should we replace Lagom's hello world example app with it?

**Comment by jroper** [comment]
Java variant here:

https://github.com/lagom/shopping-cart-java

**Comment by dwijnand** [comment]
The shopping cart sample apps will become the new default sample apps to point users to, with the hello world templates (aka https://github.com/lagom/lagom-scala.g8 and https://github.com/lagom/lagom-java.g8) will have some of their complexity removed.
