### ISSUE TITLE
Remove sbteclipse-plugin from sample apps

### ISSUE THREAD

**Issue by ignasi35** [playframework/play-meta#50]
Users should handle env-specific plugins themselves.

**Comment by ignasi35** [comment]
Done all the lagom-related projects I could find using `sbt-eclipse`.

For projects with `1.4.x` and `1.5.x` branches I only did `1.5.x`.

In Lagom itself I sent 3 separate PRs for `master`, `1.5.x` and `1.4.x`.

**Comment by ignasi35** [comment]
I did a quick and dirty attempt for `chirper` and `online-auction`. In case of [failures](https://github.com/lagom/lagom-java-sbt-chirper-example/pull/34) or extra work, I closed the PR (we're archiving the repos anyway).

**Comment by dwijnand** [comment]
Using GitHub search on the play, lagom and lightbend orgs I found 2 more repos (of low importance) as well as the 1.4.x branches for repos we don't intend to archive (the seeds and shopping cart).  So I've backported the changes on the 1.4.x branches and PRd the other 2 repos.

This effort should be complete as soon as those PRs are merged.

Nice work, Ignasi!

**Comment by ignasi35** [comment]
Thanks for the final swipe @dwijnand
