### ISSUE TITLE
Use scala-steward to keep framework and libraries updated

### ISSUE THREAD

**Issue by marcospereira** [playframework/play-meta#57]
## Play 

- [x] [playframework/playframework](https://github.com/playframework/playframework)
- [x] [playframework/play-slick](https://github.com/playframework/play-slick)
- [x] [playframework/play-doc](https://github.com/playframework/play-doc)
- [x] [playframework/twirl](https://github.com/playframework/twirl)
- [x] [playframework/scalatestplus-play](https://github.com/playframework/scalatestplus-play)
- [x] [playframework/omnidoc](https://github.com/playframework/omnidoc)
- [x] [playframework/playframework.com](https://github.com/playframework/playframework.com)
- [x] [playframework/interplay](https://github.com/playframework/interplay)
- [x] [playframework/cachecontrol](https://github.com/playframework/cachecontrol)
- [x] [playframework/play-file-watch](https://github.com/playframework/play-file-watch)
- [x] [playframework/play-json](https://github.com/playframework/play-json)
- [x] [playframework/play-ws](https://github.com/playframework/play-ws)

### Incubating
- [x] [playframework/play-grpc](https://github.com/playframework/play-grpc)
- [x] [playframework/play-socket.io](https://github.com/playframework/play-socket.io)

## Lagom
- [x] [lagom/lagom-akka-discovery-service-locator](https://github.com/lagom/lagom-akka-discovery-service-locator)

**Comment by renatocaval** [comment]
PR sent and merged in scala-steward project.
https://github.com/fthomas/scala-steward/pull/378
