### ISSUE TITLE
Auto merge for mergify backports

### ISSUE THREAD

**Issue by renatocaval** [playframework/play-meta#61]
Mergify backports are back in Play and Lagom repos, but I realised now that it's not auto-merging when the build is green. 

We need a new rule in which we don't require approval if the contributor is the mergify bot and it's on one of the stable branches.

**Comment by dwijnand** [comment]
I had configured this, but then in a recent meeting we decided to de-configure it because in the event of a merge conflict Mergify will still send a PR and that PR may pass PR validation, even though it's wrong.
