### ISSUE TITLE
Lagom samples reorganisation

### ISSUE THREAD

**Issue by dwijnand** [playframework/play-meta#67]
* [x] Complete the `lagom-samples` repo consolidation (+TemplateControl/ExampleCodeService)
* [x] Archive lagom-recipes
* [x] Archive the remaining Lagom samples
* [x] Review Lagom's docs (see [this ref](https://www.lagomframework.com/documentation/current/scala/PersistentEntity.html#Choosing-a-database))

**Comment by ignasi35** [comment]
@dwijnand I've already posted the ANN on `lagom-recipes` about the archiving and also added a quick note on README.

**Comment by dwijnand** [comment]
Completed.
