### ISSUE TITLE
2019-05-17 Play master nightly failure

### ISSUE THREAD

**Issue by dwijnand** [playframework/play-meta#77]
https://travis-ci.com/playframework/playframework/builds/112165661

code validation job failure
```
akka-stream_2.13.0-M5;2.6-20190516-231020: not found
```

doc validation job failure
```
akka-http-core_2.12;10.1.8+22-be8241d5: not found
[error] (generateMarkdownRefReport) org.parboiled.errors.ParserRuntimeException: Error while parsing action 'Root/Sequence/ZeroOrMore/Sequence/Block/FirstOf/Heading/FirstOf/AtxHeading/OneOrMore/Sequence/AtxInline/Inline/Inline_Action1' at input position (line 2, pos 3):
[error] # Configuring WS Cache
[error]   ^
[error] 
[error] org.pegdown.ParsingTimeoutException
```

microbenchmark validation job failure
```
akka-http-core_2.12;10.1.8+22-be8241d5: not found
```

publish local validation job failure
```
akka-stream_2.13.0-M5;2.6-20190516-231020: not found
```

**Comment by dwijnand** [comment]
Now I'm wondering if these suffered from an outage or blimp in Bintray file hosting.  Restarted all 4.

**Comment by dwijnand** [comment]
The microbenchmark validation job failure is the same as the 2.7.x one.

**Comment by dwijnand** [comment]
The `akka-stream_2.13.0-M5;2.6-20190516-231020: not found` failure is different.

There is no `2.6-20190516-231020` version of akka-stream_2.13.0-M5, but there _is_ a version `2.6-20190516-233030`: https://repo.akka.io/snapshots/com/typesafe/akka/akka-stream_2.13.0-M5/2.6-20190516-233030/

Note the time difference.

Our scripts use akka-actor_2.12 as a reference and it looks like the snapshots don't share the same timestamp, and therefore version.

This needs reporting upstream.

**Comment by patriknw** [comment]
The timestamp isn’t shared for different builds 2.12 and 2.13. We could fix that by picking the timestamp outside of the build. Somewhat related to https://github.com/akka/akka/issues/26675

**Comment by dwijnand** [comment]
Oh, I was just reporting in akka/akka, shall I continue?

**Comment by dwijnand** [comment]
The `ParsingTimeoutException` is probably spurious (can't reproduce locally, but maybe I'm not reproducing properly).

**Comment by dwijnand** [comment]
Forward porting the change in master to run use non-snapshots for 2.13: https://github.com/playframework/playframework/pull/9324

**Comment by dwijnand** [comment]
Closing under the assumption that everything is either spurious or handled.
