### ISSUE TITLE
Release Play 2.8.0-M2

### ISSUE THREAD

**Issue by renatocaval** [playframework/play-meta#86]
## Do the Release ([Full document](https://github.com/playframework/play-meta/blob/master/releasing/play.md))

- [x] [Release projects that Play depends on][]
  - [x] release [play-json](https://github.com/playframework/play-json/pull/281)
  - [x] release [play-ws](https://github.com/playframework/play-ws/pull/356)
  - [x] release [twirl][]

- [x] [Release Play itself][]

- [ ] [Release external modules][]
  - [x] release [play-slick][]
  - [x] release [scalatestplus-play][] https://github.com/playframework/scalatestplus-play/pull/169 https://github.com/playframework/scalatestplus-play/pull/174
  - [ ] release [play-grpc][]

- [x] [Release omnidoc][]

- [ ] ~[Update the supported modules page][]~ - not applicable
- [ ] ~[Update playframework templates and seeds][]~ - not applicable
- [ ] ~[Update Example Code Service][]~ - not applicable
- [x] [Update playframework.com][]

- [ ] [Announce][]
  - [ ] ~Write a blog post on <https://playframework.ghost.io/ghost/24> about the release.~
  - [x] Write a topic on <https://discuss.lightbend.com/>
  - [x] Write a release on <https://github.com/playframework/playframework/releases>
  - [ ] Send an internal email to eng-updates
  - [ ] Tweet about the new release.

- [x] [Post release tasks][]

[Triage issues]: https://github.com/issues?utf8=%E2%9C%93&q=label%3Atriage+org%3Aplayframework+archived%3Afalse+
[Release projects that Play depends on]: https://github.com/playframework/play-meta/blob/master/releasing/play.md#step-0---release-projects-that-play-depends-on-play-json-play-ws-twirl
[Release Play itself]: https://github.com/playframework/play-meta/blob/master/releasing/play.md#step-1---release-play-itself
[Release external modules]: https://github.com/playframework/play-meta/blob/master/releasing/play.md#step-2---release-external-modules
[Release omnidoc]: https://github.com/playframework/play-meta/blob/master/releasing/play.md#step-3---release-omnidoc
[Update the supported modules page]: https://github.com/playframework/play-meta/blob/master/releasing/play.md#step-4---update-playframework-templates-and-seeds
[Update playframework templates and seeds]: https://github.com/playframework/play-meta/blob/master/releasing/play.md#step-4---update-playframework-templates-and-seeds
[Update Example Code Service]: https://github.com/playframework/play-meta/blob/master/releasing/play.md#step-5---update-example-code-service
[Update playframework.com]: https://github.com/playframework/play-meta/blob/master/releasing/play.md#step-6---update-playframeworkcom
[Announce]: https://github.com/playframework/play-meta/blob/master/releasing/play.md#step-7---announce
[Post release tasks]: https://github.com/playframework/play-meta/blob/master/releasing/play.md#step-8---post-release-tasks

[play-grpc]: https://github.com/playframework/play-grpc
[play-json]: https://github.com/playframework/play-json
[play-slick]: https://github.com/playframework/play-slick
[play-ws]: https://github.com/playframework/play-ws
[scalatestplus-play]: https://github.com/playframework/scalatestplus-play
[twirl]: https://github.com/playframework/twirl

**Comment by mkurz** [comment]
Would be nice to get https://github.com/playframework/twirl/pull/226 into this milestone release :wink:

**Comment by marcospereira** [comment]
- We won't release play-grpc with 2.8.0-M2 because we don't have akka-grpc artifacts for Scala 2.13
- No need for a blog post since it is an M release.
- Tweet: https://twitter.com/playframework/status/1146883520163471369
- Samples updates are here: https://github.com/playframework/play-samples/pull/38

I'm closing this issue then. :-)
