### ISSUE TITLE
Move projects to dynver

### ISSUE THREAD

**Issue by octonato** [playframework/play-meta#87]
- [x] Lagom pending on https://github.com/lagom/lagom/pull/1993
- [x] [playframework/playframework](https://github.com/playframework/playframework) - https://github.com/playframework/playframework/pull/9929
- [x] [playframework/play-slick](https://github.com/playframework/play-slick) - https://github.com/playframework/play-slick/pull/526
- [x] [playframework/twirl](https://github.com/playframework/twirl) - https://github.com/playframework/twirl/pull/289
- [x] [playframework/play-doc](https://github.com/playframework/play-doc) - https://github.com/playframework/play-doc/pull/78
- [x] [playframework/scalatestplus-play](https://github.com/playframework/scalatestplus-play) - https://github.com/playframework/scalatestplus-play/pull/226
- [x] [playframework/interplay](https://github.com/playframework/interplay) - https://github.com/playframework/interplay/pull/102
- [x] [playframework/cachecontrol](https://github.com/playframework/cachecontrol) - https://github.com/playframework/cachecontrol/pull/106
- [x] [playframework/play-file-watch](https://github.com/playframework/play-file-watch) - https://github.com/playframework/play-file-watch/pull/56
---

- [ ] [playframework/omnidoc](https://github.com/playframework/omnidoc)
- [x] [playframework/playframework.com](https://github.com/playframework/playframework.com)
- [x] [playframework/play-json](https://github.com/playframework/play-json) - https://github.com/playframework/play-json/pull/380
- [x] [playframework/play-ws](https://github.com/playframework/play-ws) - https://github.com/playframework/play-ws/pull/357

**Comment by renatocaval** [comment]
I will be moving this forward in between tasks and after the 2.13 cycle.

This is to avoid loosing track.
