### ISSUE TITLE
Lagom build system features should be consolidated into the Play build system

### ISSUE THREAD

**Issue by gmethvin** [playframework/play-meta#9]
The ability to run multiple services in dev mode and having infrastructure services should exist in Play. There would probably be a different process for sbt and for Maven, since Play's support for Maven is third-party. It would also be nice to add these features to the Play Gradle plugin since customers have asked about Lagom support for Gradle.

This effectively makes the difference between "Play" and "Lagom" one of which modules are used.

**Comment by mkurz** [comment]
Still relevant...?

**Comment by ihostage** [comment]
I think that no. We have https://github.com/playframework/play-meta/issues/8 as EPIC for this.
