### ISSUE TITLE
Use latest AdoptOpenJDK patched versions in CI

### ISSUE THREAD

**Issue by dwijnand** [playframework/play-meta#93]
The Scala Team, in switching to AdoptOpenJDK in their CI, is finding a way to have CI always use the latest patched versions of AdoptOpenJDK 8 and 11 so they don't need to micro-manage nor be behind on patch versions:

* Switching to AdoptOpenJDK 8: https://github.com/scala/scala/pull/7931
* Adding AdoptOpenJDK 11: https://github.com/scala/scala/pull/8207

There is no immediate rush to implement this and, particularly, we should wait for the implementation details to settle first.  But eventually we should switch our CIs to use the same system.

**Comment by dwijnand** [comment]
Here's the jabba oneliner:

```bash
jabba install "$(jabba ls-remote "adopt@~1.$TRAVIS_JDK.0-0" --latest minor)" && jabba use "$_" && java -Xmx32m -version
```

Testing:

```bash
08:16:34 $ for TRAVIS_JDK in 8 11; do jabba ls-remote "adopt@~1.$TRAVIS_JDK.0-0" --latest minor; done
adopt@1.8.212-04
adopt@1.11.28-0
```

However(!) there are some issues with AdoptOpenJDK 11 + 12 versions in jabba: https://github.com/shyiko/jabba/issues/481 🙁

Jabba should be returning "jdk-11.0.3+7" instead of "1.11.28-0".

**Comment by dwijnand** [comment]
Even better, you can just pass the `~` version to `install`:

```bash
jabba install "adopt@~1.$TRAVIS_JDK.0-0"
```

However we can't use `$_` any more, so it becomes:

```bash
jabba install "adopt@~1.$TRAVIS_JDK.0-0" && jabba use $(jabba ls "adopt@~1.$TRAVIS_JDK.0-0" --latest minor) && java -Xmx32m -version
```

**Comment by dwijnand** [comment]
Hehe, and you can keep using `~` for `jabba use` too, so:

```bash
jabba install "adopt@~1.$TRAVIS_JDK.0-0" && jabba use "adopt@~1.$TRAVIS_JDK.0-0" && java -Xmx32m -version
```

**Comment by dwijnand** [comment]
... which is `"$_"`, so we've gone full circle:

```bash
install: jabba install "adopt@~1.$TRAVIS_JDK.0-0" && jabba use "$_" && java -Xmx32m -version
```

**Comment by ignasi35** [comment]
But doesn't 
```

install: jabba install "adopt@~1.$TRAVIS_JDK.0-0" && jabba use "$_" && java -Xmx32m -version
```
install `1.11.28-0` (instead of `1.11.0-4`, which is newer) for `TRAVIS_JDK=11`?

**Comment by marcospereira** [comment]
Another option that we discussed is to use [sdkman](https://sdkman.io/) that can install the latest version without problems. @eed3si9n has a blog post about it:

http://eed3si9n.com/all-your-jdks-on-travis-ci-using-sdkman

**Comment by dwijnand** [comment]
Yeah, that's probably the better strategy.

Unfortunately, the sdkman isn't particularly designed to be scripted around, see https://github.com/scala/scala/pull/7931#discussion_r301434372 where I explored the possible ways to do it.  I also reached out to the maintainers and they might have shipped better APIs by now.

**Comment by mkurz** [comment]
> But doesn't
> 
> ```
> 
> install: jabba install "adopt@~1.$TRAVIS_JDK.0-0" && jabba use "$_" && java -Xmx32m -version
> ```
> 
> install `1.11.28-0` (instead of `1.11.0-4`, which is newer) for `TRAVIS_JDK=11`?
> 
> (see https://github.com/lagom/lagom/pull/2199/files#diff-1d37e48f9ceff6d8030570cd36286a61L80)

This should be fixed now, see https://github.com/shyiko/jabba/issues/481#issuecomment-536038721

**Comment by marcospereira** [comment]
Mapping the state of our maintained projects:

## Play

- [ ] play-json
  - [x] master
  - [ ] 2.7.x
- [ ] interplay
  - [ ] master
- [ ] play-ws
  - [x] master
  - [x] 1.1.x
- [ ] scalatest+play
  - [x] master
  - [x] 4.0.x
- [ ] omnidoc
  - [x] master
  - [ ] 2.7.x
- [ ] play-doc
  - [x] master
  - [ ] 2.0.x
- [ ] playframework
  - [x] master
  - [x] 2.7.x
- [ ] twirl
  - [x] master
  - [x] 1.4.x
- [ ] play-file-watch
  - [ ] master playframework/play-file-watch#48
- [ ] play-samples
  - [x] 2.7.x
  - [x] 2.8.x
- [ ] cachecontrol
  - [x] master
  - [ ] 1.1.x
- [ ] play-grpc
  - [x] master
  - [ ] 0.7.x
- [ ] netty-reactive-streams
  - [x] master
- [ ] play-slick
  - [x] master
  - [ ] 4.0.x

## Lagom

- [ ] lagom
  - [x] master
  - [x] 1.5.x
- [ ] lagom-scala.g8
  - [x] 1.6.x
  - [ ] 1.5.x
- [ ] lagom-java.g8
  - [x] 1.6.x
  - [ ] 1.5.x
- [ ] lagom-samples
  - [ ] 1.6.x
  - [ ] 1.5.x

## Lightbend

- [ ] ssl-config
  - [ ] master lightbend/ssl-config#216

**Comment by dwijnand** [comment]
Change of plan:

```diff
-install: jabba install "adopt@~1.$TRAVIS_JDK.0-0" && jabba use "$_" && java -Xmx32m -version
+install: jabba install $(jabba ls-remote "adopt@~1.$TRAVIS_JDK.0-0" --latest=patch) && jabba use "$_" && java -Xmx32m -version
```

This is to ensure that the latest version, for the current "major" Java version, is used.  Previous if adopt@1.11.0-0 was already installed (via Travis CI's cache)
even though adopt@1.11.0-5 is out, we'd not install it.

Applying in Omnidoc: https://github.com/playframework/omnidoc/pull/118.

**Comment by mkurz** [comment]
We switched to The actions (even though some repos still missing) and we don't use Jabba anymore. We use coursier, which should always fetch the latest version of a jdk.
