### ISSUE TITLE
Ideas for improving flaky & unnecessary builds in Travis

### ISSUE THREAD

**Issue by octonato** [playframework/play-meta#98]
Dump here your ideas on how to improve our builds in Travis

Current problems: 

* flaky tests
* unnecessary builds due to Mergify rebasing
* full builds are executed each time, for Scala 2.12/2.13 x Java 8/11

**Comment by dwijnand** [comment]
> * flaky tests

Disable them, create dedicated issues for them and add them to the not-too-distant backlog to be addressed

> * unnecessary builds due to Mergify rebasing

https://github.com/playframework/play-meta/issues/94 Drop strict merging & re-enable branch builds

> * full builds are executed each time, for Scala 2.12/2.13 x Java 8/11

https://github.com/playframework/playframework/issues/8997 Use sbt-pull-request-validator

**Comment by renatocaval** [comment]
Totally agree with `sbt-request-validator`. We have discussed it many times, but not much action so far. 

I'm not sure about replacing smart merging will help us, if we count how many builds  run, it still produces fewer builds:

With Mergify's smart merge we have the following:

```
	 build   approved         build
PR1    √     merged
PR2    √     rebase on PR1      √
PR3    √     rebase on PR2      √

Total: 5 builds
```

If we remove it and re-enable branch builds we will have:
```
	 build   approved   build in master
PR1    √     merged 	     √
PR2    √     merged 	     √
PR3    √     merged 	     √

Total: 6 builds
```

To me, it seems that we are moving the annoyance to another place and increase the builds. The only difference is that we will be closing PRs faster.

**Comment by renatocaval** [comment]
One other thing that we have discussed is is to reduce the Scala Version / Java Version matrix.

We could pick one or a mix of the follow: 
* Scala 2.13 with Java 11 for all PRs 
* full matrix for branch builds (assuming we go back to it)
* full matrix for cron builds

**Comment by dwijnand** [comment]
I'm happy to kill branch builds if they're in the way (we can always re-run them if we want).  What's annoying is having a green PR that gets a new stupid merge commit because something was merged 20 minutes before it.

**Comment by dwijnand** [comment]
(Btw, if GitHub and Travis CI did things properly then Travis CI would set the status on the merge commit instead of the HEAD of the PR branch and GitHub would use the same merge commit when merging the PR, instead of creating a new merge commit.  That would avoid Travis CI thinking it needs to run another build.)

**Comment by marcospereira** [comment]
> What's annoying is having a green PR that gets a new stupid merge commit because something was merged 20 minutes before it.

This is the main difference here. In both cases, we are limited by the number of concurrent jobs we have in Travis, but requiring another build for PRs blocks it.

@renatocaval I'm also in doubt about how to count the builds, because there are some PRs with multiple merges builds. Shouldn't we count build like this?

```
PR 1:
    - build

PR 2:
    - build
    - PR 1 merge build

PR 3:
    - build
    - PR 1 merge build
    - PR 2 merge build (this one was missing from your count)
```

For example:

- https://github.com/playframework/playframework/pull/9442
- https://github.com/playframework/playframework/pull/9452

**Comment by dwijnand** [comment]
Ah yes, good point.  The smart merging is trumped by flaky builds.  So your PR is green, then gets an update, and then it fails, except that the failure is just a flaky test or build issue.

With branch builds the flaky tests will just be on the branches, and we'll rerun them as and when we need to verify if we had a semantic conflict.

**Comment by marcospereira** [comment]
## Travis configuration check

1. Are all the caching using caching?
2. Are all the repositories canceling builds when pushing new commits to a PR?

**Comment by marcospereira** [comment]
## Distinct requirements for PR, branch, and cron builds

Let's define requires that are more appropriate for each one of the types of builds.

### Versions

Primary and secondary versions are:

#### `master` branch

| What  | Primary  | Secondary |
|:------|:---------|:----------|
| Scala | `2.13.0` | `2.12.8`  |
| Java  | `8`      | `11`      |
| sbt   | `1`      | `0.13`    |

#### stable supported branches

| What  | Primary  | Secondary                               |
|:------|:---------|:----------------------------------------|
| Scala | `2.12.8` | `2.11.12` and `2.13.0` where applicable |
| Java  | `8`      | `11` where applicable                   |
| sbt   | `1`      | `0.13`                                  |

### Jobs for each type of build

#### pull requests

1. docs: check format and headers
1. docs: run tests
1. framework: check format, headers and binary compatibility*
1. framework: run tests using main Scala version and Java version
1. framework: run scripted tests using main sbt version and Java version

<sub>
\* These are lightweight enough to run cross scala versions
</sub>

#### branches

All pull requests jobs plus:

1. framework: run tests using secondary Scala version and main Java version
1. framework: run scripted tests using secondary sbt version and main Java version

#### crons

All branches jobs plus:

1. framework: run tests using the main Scala version and secondary Java version
1. framework: run scripted tests using main sbt version and secondary Java version

**Comment by dwijnand** [comment]
What about snapshot akka/akka http versions in cron?

**Comment by dwijnand** [comment]
@marcospereira are we adding these ideas to the sprint?  Or is the idea that we address https://github.com/playframework/play-meta/issues/94 this sprint, and more changes the sprint after?

**Comment by renatocaval** [comment]
@dwijnand, for current sprint we plan only #94. The sprint is already fat. 

We can address Marcos' suggestion on the next one.

**Comment by mkurz** [comment]
I think this issue exists in the first place because of the concurrent job limitation we had in Travis. With GitHub actions, we don't have that problem anymore. It shouldn't matter how many builds we trigger in parallel.
About flaky tests, we will see how GHA turn out. We can open issues if something turns up.
